export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const SHOW_IMPROVEMENTS = 'SHOW_IMPROVEMENTS'
export const HIDE_IMPROVEMENTS = 'HIDE_IMPROVEMENTS'

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const DEFAULT_TASK = "DEFAULT_TASK";

export const GET_TASKS_BEGIN = "GET_TASKS_BEGIN";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK_BEGIN = "DELETE_TASK_BEGIN";

export const EDIT_TASK_BEGIN = "EDIT_TASK_BEGIN";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_ERROR = "EDIT_TASK_ERROR";

export const CREATE_TASK_BEGIN = "CREATE_TASK_BEGIN";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "RLOGIN_USER_ERROR";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const SEND_EMAIL_BEGIN = "SEND_EMAIL_BEGIN";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR";

export const SEND_IMPROVEMENT_BEGIN = "SEND_IMPROVEMENT_BEGIN";
export const SEND_IMPROVEMENT_SUCCESS = "SEND_IMPROVEMENT_SUCCESS";
export const SEND_IMPROVEMENT_ERROR = "SEND_IMPROVEMENT_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const DELETE_USER_BEGIN = "DELETE_USER_BEGIN";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

